# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/openal-soft/utils/alsoft-config/CMakeLists.txt))

/Users/adriand/Documents/Dev/Vulkan/Floof-Engine/xcode-build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -H/Users/adriand/Documents/Dev/Vulkan/Floof-Engine -B/Users/adriand/Documents/Dev/Vulkan/Floof-Engine/xcode-build
