# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/assimp.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/cmake-modules/FindPkgMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/cmake-modules/FindRT.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/cmake-modules/FindZLIB.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/cmake-modules/PrecompiledHeader.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/cmake-modules/assimp-plain-config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/code/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/include/assimp/config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/revision.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/test/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/assimp/test/headercheck/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPkgConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/adriand/Documents/Dev/Vulkan/Floof-Engine/xcode-build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -H/Users/adriand/Documents/Dev/Vulkan/Floof-Engine -B/Users/adriand/Documents/Dev/Vulkan/Floof-Engine/xcode-build
