# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/entt/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/entt/cmake/in/EnTTConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/entt/cmake/in/entt.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof-Engine/Libs/entt/cmake/modules/JoinPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/BasicConfigVersion-AnyNewerVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/adriand/Documents/Dev/Vulkan/Floof-Engine/xcode-build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -H/Users/adriand/Documents/Dev/Vulkan/Floof-Engine -B/Users/adriand/Documents/Dev/Vulkan/Floof-Engine/xcode-build
